version: '3'

volumes:
   dbdata:

services:
    db:
         image: mysql:5.7
         environment:
           MYSQL_RANDOM_ROOT_PASSWORD: 1
           MYSQL_DATABASE: postcomment_db
           MYSQL_USER: dbuser
           MYSQL_PASSWORD: 123admin
         volumes:
           - dbdata:/var/lib/mysql
         restart: always

    postcomment.api:
        depends_on:
           - db
        image: postcomment.api
        build:
          context: .
        ports:
          - "8080:80"