version: '3'

volumes:
   dbdata:

services:
    db:
    db:
        image: mcmoe/mssqldocker:v2017.CU12.1
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: 1p@sswordY
          MSSQL_DB: postcommentdb
          MSSQL_USER: postcommentdb_app
          MSSQL_PASSWORD: 1p@sswordY
        ports:
            - "1433:1433"

    postcomment.api:
        depends_on:
           - db
        image: postcomment.api
        build:
          context: .
        ports:
          - "8080:80"